#!/usr/bin/env python3

from sources.ArgumentHandler import parse_args
from sources.Creator import mdCreator
import sys


def main():
    args = parse_args(sys.argv[1:])
    creator = mdCreator(args.projectName, args.language, args.gifKeywords, args.array)
    creator.launch_creator()
    return 0


if __name__ == "__main__":
    exit(main())