name: mdCreator CI
on: [push, pull_request]
jobs:
  mdCreatorBuild:
    name: Test launch mdCreator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10.8"
          token: ${{ github.token }}
          check-latest: true
          cache: "pip"
      - run: python --version

      - name: Install Python Dependencies
        run: |
          sudo apt-get update
          pip install -r requirements.txt

      - name: Run mdCreator
        run: |
          make re
          echo -ne 'y\ny' | ./mdCreator -p GithubActions -al C++

      - uses: actions/upload-artifact@v3.1.1
        with:
          path: ./README.md
