name: mdCreator CI
on: [push, pull_request]
jobs:
  mdCreatorBuild:
    name: Test launch mdCreator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
          token: ${{ github.token }}

      - name: Install Python depedencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          sudo apt-get install python3-requests
          python -m pip install requests
          pip install requests
          pip3 install requests
          pip3 install python-dotenv

      - name: Run mdCreator
        run: echo -ne 'y\ny' | ./mdCreator -p GithubActions -al C++

      - uses: actions/upload-artifact@v2
        with:
          path: |
            ./README.md
